# Node names from Nuke
MASTER_CTRL = "MASTER_CTRL"

READ_LOGO = "READ_TEAM_LOGO"
READ_BANNER = "READ_TEAM_BANNER"
READ_PODTWO = "READ_POD_TWO"
READ_PODTHREE = "READ_POD_THREE"

READ_AWAY_LOGO = "READ_AWAY_LOGO"
READ_AWAY_BANNER = "READ_AWAY_BANNER"
READ_AWAY_PODTWO = "READ_AWAY_POD_TWO"
READ_AWAY_PODTHREE = "READ_AWAY_POD_THREE"


# Team folder path
FOLDER_PATH = "y:/Workspace/MASTER_PROJECTS/CFB_15/TOOLKIT/002_3D_TEAMS/"
