DIALOG ESPNPipelineMenu
{
	NAME MAIN_DIALOG; CENTER_V; SCALE_H;

	TAB ID_STATIC
	{
		SELECTION_TABS;
		SCALE_H;

		GROUP FIRST_TAB
		{
			NAME FIRST_TAB_NAME; 
			ALIGN_TOP; 
			CENTER_H;
			COLUMNS 1;
			SPACE 4, 4;

			GROUP FIRST_TAB_GRP_01
			{
				ALIGN_TOP;
				CENTER_H;
				COLUMNS 2;
				SPACE 4, 4;

				STATICTEXT LBL_PROD_NAME { NAME LBL_PROD_NAME; CENTER_V; ALIGN_LEFT; SIZE 200, 0; }
				COMBOBOX DRP_PROD_NAME { CENTER_V; ALIGN_LEFT; SIZE 580, 0;}

				STATICTEXT LBL_PROJ_NAME { NAME LBL_PROJ_NAME; ALIGN_TOP; ALIGN_LEFT; }
				GROUP GRP_PROJ
				{
					ALIGN_TOP;
					ALIGN_LEFT;
					ROWS 3;

					EDITTEXT TXT_PROJ_NAME { ALIGN_LEFT; SIZE 600, 0; }
					CHECKBOX CHK_EXISTING { NAME CHK_EXISTING; ALIGN_LEFT; SIZE 600, 10;}
					COMBOBOX DRP_PROJ_NAME { NAME DRP_PROJ_NAME; ALIGN_LEFT; SIZE 580, 0; }
				}

				STATICTEXT LBL_SCENE_NAME { NAME LBL_SCENE_NAME; ALIGN_TOP; ALIGN_LEFT; }
				EDITTEXT TXT_SCENE_NAME { ALIGN_LEFT; SIZE 200, 0; }

				STATICTEXT LBL_FRAMERATE { NAME LBL_FRAMERATE; CENTER_V; ALIGN_LEFT; ALIGN_TOP; }
				RADIOGROUP RDO_FRAMERATE
				{
					ALIGN_LEFT;

					GROUP
					{
						COLUMNS 2;
						RADIOGADGET RDO_FRAMERATE_30 { NAME RDO_FRAMERATE_30; CENTER_H; }
						RADIOGADGET RDO_FRAMERATE_60 { NAME RDO_FRAMERATE_60; CENTER_H; }
					}
				}
			}

			GROUP FIRST_TAB_GRP_02
			{
				ALIGN_TOP;
				ALIGN_LEFT;
				ROWS 3;
				SPACE 4, 4;

				SEPARATOR FIRST_TAB_SEP_01 { SCALE_H; SIZE 820, 0;}
			}

			GROUP FIRST_TAB_GRP_03
			{
				ALIGN_TOP;
				ALIGN_LEFT;
				COLUMNS 2;
				SPACE 4, 4;

				STATICTEXT LBL_PREVIEW_PROJ { NAME LBL_PREVIEW_PROJ; ALIGN_TOP; ALIGN_LEFT; SIZE 200, 0; }
				EDITTEXT TXT_PREVIEW_PROJ { ALIGN_LEFT; SIZE 600, 0; }

				STATICTEXT LBL_PREVIEW_FILE { NAME LBL_PREVIEW_FILE; ALIGN_TOP; ALIGN_LEFT; }
				EDITTEXT TXT_PREVIEW_FILE { ALIGN_LEFT; SIZE 600, 0; }
			}

			GROUP FIRST_TAB_GRP_04
			{
				ALIGN_TOP;
				FIT_H;
				SPACE 4, 4;
				SIZE 820, 0;
				COLUMNS 2;
				ROWS 3;

				STATICTEXT LBL_NEWPROJ_EXEC { NAME LBL_NEWPROJ_EXEC; SCALE_H; ALIGN_TOP; ALIGN_RIGHT; }
				BUTTON BTN_NEWPROJ_EXEC { NAME BTN_NEWPROJ_EXEC; FIT_H; ALIGN_TOP; }

				STATICTEXT LBL_MIGPROJ_EXEC { NAME LBL_MIGPROJ_EXEC; ALIGN_TOP; ALIGN_RIGHT; }
				BUTTON BTN_MIGPROJ_EXEC { NAME BTN_MIGPROJ_EXEC; FIT_H; ALIGN_TOP; }
				
				STATICTEXT LBL_RENAME_EXEC { NAME LBL_RENAME_EXEC; ALIGN_TOP; ALIGN_RIGHT; }
				BUTTON BTN_RENAME_EXEC { NAME BTN_RENAME_EXEC; FIT_H; ALIGN_TOP; }
			}
		}

		GROUP SECOND_TAB
		{
			NAME SECOND_TAB_NAME;
			ALIGN_TOP;
			CENTER_H;
			COLUMNS 1;
			SPACE 4, 4;

			STATICTEXT SECOND_TAB_TEXT { NAME SECOND_TAB_TEXT; CENTER_V; ALIGN_LEFT; }
			EDITTEXT SECOND_TAB_TEXTBOX { CENTER_V; ALIGN_LEFT; }
		}

		GROUP THIRD_TAB
		{
			NAME THIRD_TAB_NAME;
			ALIGN_TOP;
			CENTER_H;
			COLUMNS 1;
			SPACE 4, 4;

			STATICTEXT THIRD_TAB_TEXT { NAME THIRD_TAB_TEXT; CENTER_V; ALIGN_LEFT; }
			EDITTEXT THIRD_TAB_TEXTBOX { CENTER_V; ALIGN_LEFT; }
		}

		GROUP FOURTH_TAB
		{
			NAME FOURTH_TAB_NAME;
			ALIGN_TOP;
			CENTER_H;
			COLUMNS 1;
			SPACE 4, 20;

			STATICTEXT FOURTH_TAB_TEXT { NAME FOURTH_TAB_TEXT; CENTER_V; ALIGN_LEFT; }
			EDITTEXT FOURTH_TAB_TEXTBOX { CENTER_V; ALIGN_LEFT; }
		}
	}
}